name: Playwright Visual Tests (Manual)

on:
  workflow_dispatch:

jobs:
  visual-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # 👇 Install required system dependencies for Playwright
      - name: Install Playwright system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdbus-1-3 \
            libdrm2 \
            libgbm1 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxrandr2 \
            libxshmfence1 \
            libxss1 \
            libxtst6 \
            xdg-utils \
            libffi8 \
            libx264-dev

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright visual tests
        id: run-tests
        continue-on-error: true
        run: npx playwright test --reporter=list

      - name: Upload visual diffs
        if: failure() || steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: visual-diffs
          path: test-results/**/*-diff.png
          if-no-files-found: ignore

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/