name: Playwright Visual Tests (Manual)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update apt and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2t64  # or liboss4-salsa-asound2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Playwright install
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test

      - name: Run Playwright visual tests
        id: run-tests
        continue-on-error: true
        run: npx playwright test

      - name: Upload visual diffs
        if: failure() || steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: visual-diffs
          path: test-results/**/*-diff.png
          if-no-files-found: ignore

      - name: Upload visual homepage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: homepage
          path: screenshots/homepage.png
          if-no-files-found: ignore

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report